In [1]:
import pandas as pd , matplotlib.pyplot as plt , numpy as np

In [2]:
housing = pd.read_csv('house data.csv')
#housing
#type(housing)
#housing.head()
#housing.info()

In [3]:
#housing['RM'].value_counts()

In [4]:
#housing['RAD'].value_counts()

% matplotlib inline

In [5]:
#housing.hist(bins = 50 , figsize = (20 , 15))

In [6]:
housing.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  499.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.280028   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.702279   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.884500   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208000   
75%      3.677083   12.500000   18.100000    0.000000    0.624000    6.618500   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT        MEDV  
count  506.000000  506.000000  
mean    12.653063   22.532806  
std      7.141062    9.197104  
min      1.730000    5.000000  
25%      6.950000   17.025000  
50%     11.360000   21.200000  
75%     16.955000   25.000000  
max     37.970000   50.000000

## train test spliting

In [7]:
#for learning purpose only
def split_train_test(data , test_ratio):
    np.random.seed(42)
    shuffled = np.random.permutation(len(data)) #get an array of random no. btw 1-506 
    test_set_size = int(len(data) * test_ratio) #506 * 0.2 = 101
    
    test_indices = shuffled[:test_set_size] #array of lenth 101 of random no btw 1-506
    
    train_indices = shuffled[test_set_size:] #array of lenth 405 of random no btw 1-506 which does not in test_indices

    
    return data.iloc[train_indices] , data.iloc[test_indices]
    

In [8]:
train_set , test_set = split_train_test(housing , 0.2)

In [9]:
#print(f'rows in train set : {len(train_set)}  \n\n rows in test set : {len(test_set)} ')

## use of sklearn for this 

In [10]:
from sklearn.model_selection import StratifiedShuffleSplit

In [11]:
# this will make the ratio same in test and train set in CHAS field
split = StratifiedShuffleSplit(n_splits = 1 , test_size = 0.2 , random_state = 42)
split = split.split(housing , housing['CHAS'])

for train_index , test_index in split:
    #print(train_index ,'           ', test_index)
    strat_test_set = housing.loc[test_index]
    strat_train_set = housing.loc[train_index]

In [12]:
strat_train_set['CHAS'].value_counts()
(376 / 28)

13.428571428571429

In [13]:
strat_test_set['CHAS'].value_counts()
95/7

13.571428571428571

In [14]:
housing = strat_train_set.copy()

# looking for coreltions

In [15]:
corr_matrix = housing.corr()
#corr_matrix
' + (0 > )= proportion '
'- (0 < ) = inversely proportional'
corr_matrix['MEDV'].sort_values(ascending = False)
#strong positive correalation = value increase as function increase

MEDV       1.000000
RM         0.674171
B          0.361761
ZN         0.339741
DIS        0.240451
CHAS       0.205066
AGE       -0.364596
RAD       -0.374693
CRIM      -0.393715
NOX       -0.422873
TAX       -0.456657
INDUS     -0.473516
PTRATIO   -0.493534
LSTAT     -0.740494
Name: MEDV, dtype: float64

In [16]:
from pandas.plotting import scatter_matrix

In [17]:
attributes = ['RM' , 'MEDV' , 'ZN' ,'LSTAT']
#scatter_matrix(housing[attributes] , figsize = (12,8))

In [18]:
#housing.plot(kind ='scatter' , x ='RM' , y = 'MEDV' , alpha = 0.6) 

In [19]:
#housing.plot(kind ='scatter' , x ='LSTAT' , y = 'MEDV' , alpha = 0.6) 

In [20]:
#housing.plot(kind ='scatter' , x ='CHAS' , y = 'MEDV' , alpha = 0.6) 

In [21]:
#housing.plot(kind ='scatter' , x ='TAX' , y = 'MEDV' , alpha = 0.6) 

# trying out attribute combinationn

In [22]:
housing['TaxRm'] = housing['TAX'] / housing['RM']

In [23]:
housing.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  \
254  0.04819  80.0   3.64     0  0.392  6.108  32.0  9.2203    1  315   
348  0.01501  80.0   2.01     0  0.435  6.635  29.7  8.3440    4  280   
476  4.87141   0.0  18.10     0  0.614  6.484  93.6  2.3053   24  666   
321  0.18159   0.0   7.38     0  0.493  6.376  54.3  4.5404    5  287   
326  0.30347   0.0   7.38     0  0.493  6.312  28.9  5.4159    5  287   

     PTRATIO       B  LSTAT  MEDV       TaxRm  
254     16.4  392.89   6.57  21.9   51.571709  
348     17.0  390.94   5.99  24.5   42.200452  
476     20.2  396.21  18.68  16.7  102.714374  
321     19.6  396.90   6.87  23.1   45.012547  
326     19.6  396.90   6.15  23.0   45.468948

In [24]:
corr_matrix = housing.corr()
corr_matrix['MEDV'].sort_values(ascending = False)

MEDV       1.000000
RM         0.674171
B          0.361761
ZN         0.339741
DIS        0.240451
CHAS       0.205066
AGE       -0.364596
RAD       -0.374693
CRIM      -0.393715
NOX       -0.422873
TAX       -0.456657
INDUS     -0.473516
PTRATIO   -0.493534
TaxRm     -0.526507
LSTAT     -0.740494
Name: MEDV, dtype: float64

In [25]:
#housing.plot(kind ='scatter' , x ='TaxRm' , y = 'MEDV' , alpha = 0.6) 

In [26]:
#housing.plot(kind ='scatter' , x ='RM' , y = 'TAX' , alpha = 0.6) 

In [27]:
housing = strat_train_set.drop('MEDV' , axis = 1)
housing_labels = strat_train_set['MEDV'].copy()

In [28]:
housing_labels

254    21.9
348    24.5
476    16.7
321    23.1
326    23.0
       ... 
155    15.6
423    13.4
98     43.8
455    14.1
216    23.3
Name: MEDV, Length: 404, dtype: float64

# missing aatributes


# to take care of missing attribute in any field
we have 3 option :
# 1 - get rid of the data points
# 2 - get rid of the whole attributes
# 3 - set the value to be 0 , median or some sensible value

In [29]:
#1-option
a = housing.dropna(subset = ['RM'] ).shape
print(a)
housing.shape


(397, 13)


(404, 13)

In [30]:
#2 - option
housing.drop('RM' , axis=1).shape

(404, 12)

In [31]:
#3 - option
median = housing['RM'].median() 
median
housing['RM'].fillna(median)


254    6.108
348    6.635
476    6.484
321    6.376
326    6.312
       ...  
155    6.152
423    6.103
98     7.820
455    6.525
216    5.888
Name: RM, Length: 404, dtype: float64


# #doing same with sklearn

In [32]:
#before imputing
#housing.describe()

In [33]:
from sklearn.impute import SimpleImputer

#calculate median for every column
imputer = SimpleImputer(strategy = 'median')
imputer.fit(housing)

SimpleImputer(strategy='median')

In [34]:
#give the list of medians for every column
imputer.statistics_

array([2.86735e-01, 0.00000e+00, 9.90000e+00, 0.00000e+00, 5.38000e-01,
       6.20900e+00, 7.82000e+01, 3.12220e+00, 5.00000e+00, 3.37000e+02,
       1.90000e+01, 3.90955e+02, 1.15700e+01])

In [35]:
x = imputer.transform(housing)

In [36]:
x

array([[4.81900e-02, 8.00000e+01, 3.64000e+00, ..., 1.64000e+01,
        3.92890e+02, 6.57000e+00],
       [1.50100e-02, 8.00000e+01, 2.01000e+00, ..., 1.70000e+01,
        3.90940e+02, 5.99000e+00],
       [4.87141e+00, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        3.96210e+02, 1.86800e+01],
       ...,
       [8.18700e-02, 0.00000e+00, 2.89000e+00, ..., 1.80000e+01,
        3.93530e+02, 3.57000e+00],
       [4.75237e+00, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        5.09200e+01, 1.81300e+01],
       [4.56000e-02, 0.00000e+00, 1.38900e+01, ..., 1.64000e+01,
        3.92800e+02, 1.35100e+01]])

In [37]:
housing_tr = pd.DataFrame(x , columns = housing.columns)
housing_tr

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS   RAD    TAX  \
0    0.04819  80.0   3.64   0.0  0.392  6.108  32.0  9.2203   1.0  315.0   
1    0.01501  80.0   2.01   0.0  0.435  6.635  29.7  8.3440   4.0  280.0   
2    4.87141   0.0  18.10   0.0  0.614  6.484  93.6  2.3053  24.0  666.0   
3    0.18159   0.0   7.38   0.0  0.493  6.376  54.3  4.5404   5.0  287.0   
4    0.30347   0.0   7.38   0.0  0.493  6.312  28.9  5.4159   5.0  287.0   
..       ...   ...    ...   ...    ...    ...   ...     ...   ...    ...   
399  3.53501   0.0  19.58   1.0  0.871  6.152  82.6  1.7455   5.0  403.0   
400  7.05042   0.0  18.10   0.0  0.614  6.103  85.1  2.0218  24.0  666.0   
401  0.08187   0.0   2.89   0.0  0.445  7.820  36.9  3.4952   2.0  276.0   
402  4.75237   0.0  18.10   0.0  0.713  6.525  86.5  2.4358  24.0  666.0   
403  0.04560   0.0  13.89   1.0  0.550  5.888  56.0  3.1121   5.0  276.0   

     PTRATIO       B  LSTAT  
0       16.4  392.89   6.57  
1       17.0  390.94   5.99  
2       20.2  396.21  18.68  
3       19.6  396.90   6.87  
4       19.6  396.90   6.15  
..       ...     ...    ...  
399     14.7   88.01  15.02  
400     20.2    2.52  23.29  
401     18.0  393.53   3.57  
402     20.2   50.92  18.13  
403     16.4  392.80  13.51  

[404 rows x 13 columns]

# scikit-learn Design

## primary three types of objects

### 1 - estimators : it estimates some parameters besed on a a dataset . Ex - imputer  it has a fit method and transform method, 
### fit method - fits the dataset and calculate internal parameters

### 2 - Transformers : takes input and returns output based on the learnings from fit() . It also has a convelence function function called fit_transform(). which fits and then transforms.

### 3 - Predictors : ex - linearRegression model , fit() and predict () are two common fuctions . It also gives score() fun which will evaluate the predictions. 

# ** Feature scaling
## 1. normalization = Min - Max scaling  [ (value - min) / (value-max) ] . Sclearn provide a class called MinMaxScaler for this

## 2 . Standardization = (value - mean) / std . Sklearn provides StandardScaler for this

# * Creating a pipeline

In [38]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

my_pipeline = Pipeline([
    ('imputer' , SimpleImputer(strategy = 'median')) , 
    # add as many as want in pipeline
    ('std_scaler' , StandardScaler())
])



In [39]:
housing_num_tr = my_pipeline.fit_transform(housing)
housing_num_tr


array([[-0.43942006,  3.12628155, -1.12165014, ..., -0.97491834,
         0.41164221, -0.86091034],
       [-0.44352175,  3.12628155, -1.35893781, ..., -0.69277865,
         0.39131918, -0.94116739],
       [ 0.15682292, -0.4898311 ,  0.98336806, ...,  0.81196637,
         0.44624347,  0.81480158],
       ...,
       [-0.43525657, -0.4898311 , -1.23083158, ..., -0.22254583,
         0.41831233, -1.27603303],
       [ 0.14210728, -0.4898311 ,  0.98336806, ...,  0.81196637,
        -3.15239177,  0.73869575],
       [-0.43974024, -0.4898311 ,  0.37049623, ..., -0.97491834,
         0.41070422,  0.09940681]])

## Selecting a desired model for Dragon REal EStates

In [41]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

#model = LinearRegression()
#model = DecisionTreeRegressor()

model = RandomForestRegressor()

model.fit(housing_num_tr , housing_labels)

RandomForestRegressor()

In [42]:
some_data = housing.iloc[:5]
some_labels = housing_labels.iloc[:5]

In [43]:
prepared_data = my_pipeline.transform(some_data)

In [44]:
model.predict(prepared_data)

array([22.262, 25.193, 16.586, 23.515, 23.482])

In [45]:
list(some_labels)

[21.9, 24.5, 16.7, 23.1, 23.0]

# Evaluating the model

In [46]:
from sklearn.metrics import mean_squared_error as mse

housing_predictions = model.predict(housing_num_tr)
mse = mse(housing_labels , housing_predictions)
rmse = np.sqrt(mse)

rmse  #over fitting

#housing_predictions

1.3016272317737692

# using better evaluating technique - Cross Validation

In [47]:
from sklearn.model_selection import cross_val_score as cvs

scores = cvs(model , housing_num_tr , housing_labels , scoring = 'neg_mean_squared_error' , cv =10)
rmse_scores = np.sqrt(-scores)

rmse_scores 

array([2.88628438, 2.64293509, 4.46922831, 3.57282674, 3.09322124,
       2.85295097, 4.64024221, 3.44424826, 3.0274768 , 3.74022437])

In [48]:
def print_scores(scores):
    print('scores : ' , scores)
    print('Mean :', scores.mean())
    print('Standard dev :',scores.std())

In [49]:
print_scores(rmse_scores)

scores :  [2.88628438 2.64293509 4.46922831 3.57282674 3.09322124 2.85295097
 4.64024221 3.44424826 3.0274768  3.74022437]
Mean : 3.436963838373805
Standard dev : 0.6468822679505505


# Sklearn Joblib

## saving the model

In [50]:
from joblib import dump , load

dump(model , 'Real Estate.joblib') #dump(value, filename, compress=0, protocol=None, cache_size=None)

In [68]:
from sklearn.metrics import mean_squared_error as mse

x_test = strat_test_set.drop('MEDV' , axis = 1)
y_test = strat_test_set['MEDV'].copy()

x_test_prepared = my_pipeline.transform(x_test)

final_predictions = model.predict(x_test_prepared)

final_mse = mse(y_test , final_predictions)
final_rmse = np.sqrt(final_mse)


In [69]:
final_rmse

2.9523697145466965

In [62]:
#x_test , y_test



(102, 13)

In [63]:
x_test_prepared.shape 

(102, 13)

In [75]:
print('pridicted : ',final_predictions ,'\n\n actual :' ,list(y_test))

pridicted :  [24.023 11.435 25.532 21.994 18.67  15.05  19.779 15.058 32.398 40.054
 19.285 12.121 25.089 23.061 19.724 11.383 30.977 14.33  23.56  19.025
 19.902 17.793 14.514 21.958 18.524 32.261 16.325 33.432  8.875 33.87
 23.937 21.443 23.441 10.855 21.25  10.851 41.686 24.653 23.933 41.939
 23.942 29.187 20.281 20.824 18.534 33.044 44.432 20.495 20.348 22.1
 21.345 14.66  20.787 15.57  24.638 33.8   41.589 29.518 18.817 21.042
 46.407  9.677 18.847 25.147 15.234 32.939 20.329 17.595 18.961 34.032
 29.813 22.992 21.692 22.674 34.979 12.948 15.655 20.198 21.055 21.312
 22.437 21.383 14.061 22.871 20.283 21.495 14.089 21.275 21.916 23.103
 18.622 26.375  7.195 25.895 18.673 29.905 19.512 31.14  14.452 27.278
 20.894 20.38 ] 

 actual : [16.5, 10.2, 30.1, 23.0, 14.4, 15.6, 19.4, 14.1, 30.3, 35.2, 23.1, 13.8, 25.0, 27.9, 19.5, 12.3, 32.2, 13.5, 23.8, 21.7, 19.2, 19.5, 10.4, 23.2, 18.6, 28.5, 15.2, 32.0, 7.2, 34.6, 20.1, 20.6, 23.6, 13.1, 23.8, 12.7, 43.1, 24.7, 22.2, 44.0, 28.1, 31.0, 

In [65]:
final_predictions.shape

(102,)

In [77]:
prepared_data.shape

(5, 13)

In [78]:
prepared_data

array([[-0.43942006,  3.12628155, -1.12165014, -0.27288841, -1.42262747,
        -0.23369338, -1.31238772,  2.61111401, -1.0016859 , -0.5778192 ,
        -0.97491834,  0.41164221, -0.86091034],
       [-0.44352175,  3.12628155, -1.35893781, -0.27288841, -1.0542567 ,
         0.51312363, -1.3938808 ,  2.19312325, -0.65766683, -0.78557904,
        -0.69277865,  0.39131918, -0.94116739],
       [ 0.15682292, -0.4898311 ,  0.98336806, -0.27288841,  0.47919371,
         0.29914001,  0.87020968, -0.68730678,  1.63579367,  1.50571521,
         0.81196637,  0.44624347,  0.81480158],
       [-0.42292925, -0.4898311 , -0.57719868, -0.27288841, -0.5573845 ,
         0.14609212, -0.52225911,  0.37882487, -0.5429938 , -0.74402708,
         0.52982668,  0.45343469, -0.81939807],
       [-0.40786253, -0.4898311 , -0.57719868, -0.27288841, -0.5573845 ,
         0.05539708, -1.42222622,  0.79643404, -0.5429938 , -0.74402708,
         0.52982668,  0.45343469, -0.91902752]])

In [79]:
prepared_data[0]

array([-0.43942006,  3.12628155, -1.12165014, -0.27288841, -1.42262747,
       -0.23369338, -1.31238772,  2.61111401, -1.0016859 , -0.5778192 ,
       -0.97491834,  0.41164221, -0.86091034])

## using the model 

In [80]:
from joblib import dump , load
import numpy as np

model =load('Real Estate.joblib') 

# input = prepared_data[0]

features = np.array([[-0.43942006,  3.12628155, -1.12165014, -0.27288841, -1.42262747,
       -0.23369338, -1.31238772,  2.61111401, -1.0016859 , -0.5778192 ,
       -0.97491834,  0.41164221, -0.86091034]])



pridicted_price = model.predict(features)
pridicted_price

array([22.262])