In [1]:
import pandas as pd
import numpy as  np

In [4]:
df = pd.read_csv('house_data.csv')
df.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   
3  2487200875  20141209T000000  604000.0         4       3.00         1960   
4  1954400510  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view  ...  grade  sqft_above  sqft_basement  \
0      5650     1.0           0     0  ...      7        1180              0   
1      7242     2.0           0     0  ...      7        2170            400   
2     10000     1.0           0     0  ...      6         770              0   
3      5000     1.0           0     0  ...      7        1050            910   
4      8080     1.0           0     0  ...      8        1680              0   

   yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0      1955             0    98178  47.5112 -122.257           1340   
1      1951          1991    98125  47.7210 -122.319           1690   
2      1933             0    98028  47.7379 -122.233           2720   
3      1965             0    98136  47.5208 -122.393           1360   
4      1987             0    98074  47.6168 -122.045           1800   

   sqft_lot15  
0        5650  
1        7639  
2        8062  
3        5000  
4        7503  

[5 rows x 21 columns]

In [5]:
df.drop(['id' , 'date'] , axis = 1, inplace = True)

In [7]:
#dropping null rows 
df = df.dropna(axis = 0 )

# 1. Min Max Normalizing

In [8]:
#min max normalise

from sklearn import preprocessing
data = {'rupaye' : [45 , 5 , 334, 23 , 43 , 56]}
rupaye_frame = pd.DataFrame(data)

min_max_normalizer = preprocessing.MinMaxScaler()
scaled_data = min_max_normalizer.fit_transform(rupaye_frame)
#scaled_data = min_max_normalizer.transform(test_frame)
rupaye_frame_normalized = pd.DataFrame(scaled_data)
rupaye_frame_normalized


0
0  0.121581
1  0.000000
2  1.000000
3  0.054711
4  0.115502
5  0.155015

# 2. z-score normalization ->
 this process is based on mean and variance of data ,after normalizing mean of data is 0 and variance is 1


In [9]:


from sklearn import preprocessing
data = {'rupaye' : [45 , 5 , 334, 23 , 43 , 56]}
rupaye_frame = pd.DataFrame(data)
min_max_normalizer = preprocessing.scale(rupaye_frame)
#min_max_normalizer
#scaled_data = min_max_normalizer.fit_transform(rupaye_frame)
# #scaled_data = min_max_normalizer.transform(test_frame)
rupaye_frame_normalized = pd.DataFrame(min_max_normalizer , columns = ['rupaye'])
rupaye_frame_normalized

rupaye
0 -0.348462
1 -0.702830
2  2.211847
3 -0.543364
4 -0.366180
5 -0.251011

# bining numerical features


In [10]:

data = {'age' : [45 , 5 , 34, 23 , 43 , 56 , 6 , 42, 7]}
age_frame = pd.DataFrame(data)

bins = [0 , 20 , 40   , 60  , 80]
group_name = [ 'less than 20 yeas ' , ' 20 - 40 years' , '40-60 years' , '60+']

age_frame['categories'] = pd.cut(age_frame['age'] , bins , labels = group_name )
age_frame

age          categories
0   45         40-60 years
1    5  less than 20 yeas 
2   34       20 - 40 years
3   23       20 - 40 years
4   43         40-60 years
5   56         40-60 years
6    6  less than 20 yeas 
7   42         40-60 years
8    7  less than 20 yeas

# 4. One hot encoding

In [11]:
#creating dummy variable form categorical data
dummy_frame = pd.get_dummies(age_frame.categories)
dummy_frame

less than 20 yeas    20 - 40 years  40-60 years    60+
0               False           False         True  False
1                True           False        False  False
2               False            True        False  False
3               False            True        False  False
4               False           False         True  False
5               False           False         True  False
6                True           False        False  False
7               False           False         True  False
8                True           False        False  False

# 5. Label Encoding

In [12]:
#converting categorial value to numerical
from sklearn import preprocessing

encoder = preprocessing.LabelEncoder()
encoder.fit_transform(['delhi' , 'pune' , 'mumbai' , 'delhi'])
encoder.inverse_transform([2,1,1,0])

array(['pune', 'mumbai', 'mumbai', 'delhi'], dtype='<U6')

In [ ]:
#analysing by date

In [13]:
startDate = '2017-11-18'
endDate = '2017-12-18'
dates = pd.DataFrame(pd.date_range(startDate , endDate) , columns = ['Dates'])
dates[:5]

Dates
0 2017-11-18
1 2017-11-19
2 2017-11-20
3 2017-11-21
4 2017-11-22

# creating word counter vector
transform a given text into a vector on the basis of the frequency (count) of each word that occurs in the entire text


In [15]:
from sklearn.feature_extraction.text import CountVectorizer

In [19]:
comments = ['nice product' , 'bad condition' , 'shipping was bad' , 'great delivery' ]
count_vect = CountVectorizer()

# Printing the identified Unique words along with their indices
X_train_counts = count_vect.fit(comments)
X_train_counts.vocabulary_

#word_frame = pd.DataFrame(X_train_counts.toarray())
#word_frame #Sparse Matrix.

vector = X_train_counts.transform(comments)
  
# Summarizing the Encoded Texts
print("Encoded Document is:")
vector = vector.toarray()
print(vector)

Encoded Document is:
[[0 0 0 0 1 1 0 0]
 [1 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 1 1]
 [0 0 1 1 0 0 0 0]]
